### ISSUE TITLE
filter by namespace in URL?

### ISSUE THREAD

**Issue by mlkmhd** [kubeshark/front#2]
Hi there,

Is it possible to filter requests by namespace in the URL path? 

for example I like to see the requests in the `test` namespace like this: `http://localhost:8899?filters="namespace=='test'"`

I know how to filter by namespace in the kubeshark command but I like to expose the ui to other teams as a link to see their traffics

**Comment by mertyildiran** [comment]
It was actually in my TODO list and it's implemented with https://github.com/kubeshark/front/commit/75e028cbccd8ae8bf4b71abf2bbce9595f9b7b2b
