### ISSUE TITLE
BUG: Missing quote-end when adding a KFL statement part in the UI.

### ISSUE THREAD

**Issue by alongir** [kubeshark/front#7]
When I press the "+" button on the source service, the statement is missing a `"`

<img width="659" alt="image" src="https://user-images.githubusercontent.com/1990761/231842380-cc5b3e9d-c497-4d33-b41f-3cd34750edba.png">

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1990761/231842443-23a29c5b-a68b-43ed-9520-41d1ebfaa105.png">

**Comment by mertyildiran** [comment]
Fixed with https://github.com/kubeshark/front/commit/df358a375ae49ecb0c366f16bda75946ee1fb2f9
